#!/bin/bash
# vim: ts=4 sts=4 syntax=sh et sw=4 sr smartindent:
# kafka-proxy	Init file for kafka rest proxy
# description: kafka-proxy
# chkconfig: 2345 98 02

PATTERN='(kafkarest\.Main)|(kafkarest\.KafkaRestMain)'

start() {
	if isRunning; then
		echo "Service is already running"
        return
	fi
    echo -n "Starting : "
    nohup /usr/bin/kafka-rest-start /etc/kafka-rest/kafka-proxy.properties &
    return
}

stop() {
    echo -n "Shutting down : "
    /usr/bin/kafka-rest-stop
    sleep 2
    return
}

status() {
	if ! isRunning; then
  	  	echo "Stopped"
		return
	fi
	echo "Running"
	return
}

isRunning() {
	TARGET=`ps ax | egrep -i $PATTERN | grep java | grep -v grep | awk '{print $1}'`
	if [ "x$TARGET" = "x" ]; then
  	  	return 1
	fi
	return 0
}

case "$1" in
    start)
        start
        ;;
    stop)
        stop
        ;;
    status)
	status
        ;;
    restart)
        stop
        start
        ;;
    *)
        echo "Usage:  {start|stop|status|restart}"
        exit 1
        ;;
esac
exit $?
